
[tool.black]
target-version = ["py310"]

[tool.coverage.report]
omit = ["*/migrations/*"]

[tool.coverage.run]
branch = true
include = ["pepysdiary/*"]
omit = ["*/migrations/*.py"]

[tool.isort]
profile = "black"
